### ISSUE TITLE
Landing page viewport

### ISSUE THREAD

**Issue by whysofast** [joaovictornsv/climate-app#2]
Here I am again to talk about sizes hahahaha 
![image](https://user-images.githubusercontent.com/39545472/97237539-1a787f00-17c6-11eb-9191-ae15a99ea834.png)

Decrease the viewport a little bit :dancers:

**Comment by joaovictornsv** [comment]
Thanks one more time Matheus kkkk, I corrected the sizes, it's working perfectly
